<td valign="top" class="header" colspan=2>
</td>
</tr>
<tr>
<td valign="top" colspan="2" class="menuline"> 
<div align="center">
<font size="5" color=navy>Уважаемые Дамы и Господа!</font>
</div>
<div align="center"> 
<font face="Tahoma" size="2"><b>Адрес для личного обращения:</b></font>
<p><font face="Tahoma" size="2"><?=$address?></font></p>
<p><img src="pics/astragal.jpg"></p> 
<p><b><font size="2" face="Tahoma">Для резюме и информационных сообщений:</font></b></p>
<p><font size="2" face="Tahoma">Email: <a href="mailto:<?=$email2?>"><?=$email2?></a><br>
<p><font face="Tahoma" size="2"><b>Руководитель компании 
</b> Сергун Оксана Юрьевна<br>
<?
/*
$winstat='width=750 height=500 toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=1,resizable=1';
$kav="'";
$i=1;
$about='about.php';
echo'<a href='.$kav.$about.$kav.' target="1" onclick="window.open('.$kav.$about.$kav.', '.$kav.$i.$kav.', '.$kav.$winstat.$kav.');">Сергун Оксана Юрьевна</a>';
*/
?>
<br>
<?=$tel1?><br>
<?=$tel2?><br>
</div>
</div>
</td>