<tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/?id=news'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Новости сайта
</td>
</tr>
<tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/?id=about'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
О компании 
</td>
</tr>
<tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/?id=contacts'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Координаты компании 
</td>
</tr>
<tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='mailto:astragal@ua.fm'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Е-mail 
</td>
</tr>