<tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/recruiting?id=vacance'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Вакансии
</td>
</tr>
<tr> 
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/recruiting?id=resume'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Резюме
</td>
</tr>
<tr> 
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/recruiting?id=anketa'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
анкета для соискателя
</td>
</tr>
<tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/recruiting?id=sworker'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
заявка для работодателя
</td> 
</tr>