<tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/training?id=seminars'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Семинары
</td>
</tr>
<tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/training?id=training'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Тренинги
</td> 
</tr>
<tr> 
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/training?id=tests'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Тестирование
</td> 
</tr>
<tr> 
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/training?id=kursisti'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Курсисты
</td>
</tr>