<form  method="post" target="_blank" action='http://<?=$host?>/recruiting/addresum.php'>
<table cellpadding="3" cellspacing="0" border="0" bgcolor='#E5E5E5' width=98% align=center>
<td colspan="2"><marquee><font color="red"><b>УБЕДИТЕЛЬНО ПРОСИМ ВАС ВНИМАТЕЛЬНО ЗАПОЛНЯТЬ ДАННЫЕ!</b></font></marquee><br></td>
</tr>
<tr>
<td valign="top" class="header" colspan=2>
В КАКИХ СФЕРАХ ДЕЯТЕЛЬНОСТИ У ВАС ЕСТЬ ОПЫТ РАБОТЫ (можно указать от 1 до 3):
</td>
</tr>
<tr>
<td colspan="2">
<select name="sfera1">
<option selected>торговля продукты питания</option>
<option>торговля тнп</option>
<option>торговля техника</option>
<option>торговля телекоммуникации и связь</option>
<option>торговля розничная</option>
<option>кадровые службы, рекрутинг</option>
<option>секреториат, ахо</option>
<option>информационно - технические службы</option>
<option>импорт, экспорт</option>
<option>логистика, таможня, склад</option>
<option>перевозки, автобизнес</option>
<option>производство продуктов питания</option>
<option>производство швейное</option>
<option>производство мебельное</option>
<option>производство разное</option>
<option>медицина, косметология, фармация</option>
<option>бухгалтерия и аудит</option>
<option>финансы и ценные бумаги</option>
<option>банковская  сфера</option>
<option>юриспруденция и нотариат</option>
<option>информационные технологии</option>
<option>страхование</option>
<option>строительство,  ремонт, архитектура</option>
<option>недвижимость</option>
<option>сми: телевидение, радиовещание, пресса</option>
<option>реклама, дизайн, общественные связи</option>
<option>издательское дело и полиграфия</option>
<option>маркетинг</option>
<option>охрана и безопасность</option>
<option>туристический бизнес</option>
<option>игорный и шоу бизнес, досуг, мода, спорт</option>
<option>охрана и безопасность</option>
<option>гостиничный бизнес</option>
<option>общественное питание и ресторанный бизнес</option>
<option>бытовое и жилищно - комунальное обслуживание</option>
<option>воспитание, образование</option>
<option>научно - исследовательская и проектно - конструкторская деятельность</option>
<option>аварийно - спасательные и пожарные службы</option>
<option>культура и искусство</option>
<option>геология, геодезия, картография</option>
<option>благотворительная, социальная, религиозная и культурная деятельность</option>
<option>санитария, эпидемиология, мониторинг окружающей среды</option>
<option>работа за рубежом</option>
<option>работа, не требующая специальной подготовки, и - у  частных лиц</option>
<option>разное</option>
</select>
<br>
<br>
<select name="sfera2">
<option selected>данных нет</option>
<option>торговля продукты питания</option>
<option>торговля тнп</option>
<option>торговля техника</option>
<option>торговля телекоммуникации и связь</option>
<option>торговля розничная</option>
<option>кадровые службы, рекруитмент</option>
<option>секреториат, ахо</option>
<option>информационно - технические службы</option>
<option>импорт, экспорт</option>
<option>информационные технологии</option>
<option>логистика, таможня, склад</option>
<option>перевозки, автобизнес</option>
<option>производство продуктов питания</option>
<option>производство швейное</option>
<option>производство мебельное</option>
<option>производство разное</option>
<option>медицина, косметология, фармация</option>
<option>бухгалтерия и аудит</option>
<option>финансы и ценные бумаги</option>
<option>банковская  сфера</option>
<option>юриспруденция и нотариат</option>
<option>страхование</option>
<option>строительство,  ремонт, архитектура</option>
<option>недвижимость</option>
<option>сми: телевидение, радиовещание, пресса</option>
<option>реклама, дизайн, общественные связи</option>
<option>издательское дело и полиграфия</option>
<option>маркетинг</option>
<option>охрана и безопасность</option>
<option>туристический бизнес</option>
<option>игорный и шоу бизнес, досуг, мода, спорт</option>
<option>охрана и безопасность</option>
<option>гостиничный бизнес</option>
<option>общественное питание и ресторанный бизнес</option>
<option>бытовое и жилищно - комунальное обслуживание</option>
<option>воспитание, образование</option>
<option>научно - исследовательская и проектно - конструкторская деятельность</option>
<option>аварийно - спасательные и пожарные службы</option>
<option>культура и искусство</option>
<option>геология, геодезия, картография</option>
<option>благотворительная, социальная, религиозная и культурная деятельность</option>
<option>санитария, эпидемиология, мониторинг окружающей среды</option>
<option>работа за рубежом</option>
<option>работа, не требующая специальной подготовки, и - у  частных лиц</option>
<option>разное</option>
</select>
<br>
<br>
<select name="sfera3">
<option selected>данных нет</option>
<option>торговля продукты питания</option>
<option>торговля тнп</option>
<option>торговля техника</option>
<option>торговля телекоммуникации и связь</option>
<option>торговля розничная</option>
<option>кадровые службы, рекруитмент</option>
<option>секреториат, ахо</option>
<option>информационно - технические службы</option>
<option>импорт, экспорт</option>
<option>информационные технологии</option>
<option>логистика, таможня, склад</option>
<option>перевозки, автобизнес</option>
<option>производство продуктов питания</option>
<option>производство швейное</option>
<option>производство мебельное</option>
<option>производство разное</option>
<option>медицина, косметология, фармация</option>
<option>бухгалтерия и аудит</option>
<option>финансы и ценные бумаги</option>
<option>банковская  сфера</option>
<option>юриспруденция и нотариат</option>
<option>страхование</option>
<option>строительство,  ремонт, архитектура</option>
<option>недвижимость</option>
<option>сми: телевидение, радиовещание, пресса</option>
<option>реклама, дизайн, общественные связи</option>
<option>издательское дело и полиграфия</option>
<option>маркетинг</option>
<option>охрана и безопасность</option>
<option>туристический бизнес</option>
<option>игорный и шоу бизнес, досуг, мода, спорт</option>
<option>охрана и безопасность</option>
<option>гостиничный бизнес</option>
<option>общественное питание и ресторанный бизнес</option>
<option>бытовое и жилищно - комунальное обслуживание</option>
<option>воспитание, образование</option>
<option>научно - исследовательская и проектно - конструкторская деятельность</option>
<option>аварийно - спасательные и пожарные службы</option>
<option>культура и искусство</option>
<option>геология, геодезия, картография</option>
<option>благотворительная, социальная, религиозная и культурная деятельность</option>
<option>санитария, эпидемиология, мониторинг окружающей среды</option>
<option>работа за рубежом</option>
<option>работа, не требующая специальной подготовки, и - у  частных лиц</option>
<option>разное</option>
</select>
<input type="hidden" name="sfera4" value="данных нет">
<input type="hidden" name="sfera5" value="данных нет">
</td>
</tr>
<tr>
<td valign="top" class="header" colspan=2>
КОНТАКТНАЯ ИНФОРМАЦИЯ:
</td>
</tr>
<tr valign="top" colspan=2> 
<td colspan="2">Фамилия 
<input type="text" name="fiof">
Имя 
<input type="text" name="fioi">
Отчество 
<input type="text" name="fioo">
</td>
</tr>
<tr> 
<td valign="top" colspan="2">
телефон: 
<input type="text"  name="telcontact">
факс: 
<input type="text" value="нет" name="faxcotact">
E-mail: 
<input type="text" value="нет" name="emailcont" size="20">
<input type="hidden" name="fiorecom" value="нет">
<input type="hidden" name="firmdolgrecom" value="нет">
<input type="hidden" name="telrecom" value="нет">
<input type="hidden" name="telcontdom" value="нет">
<input type="hidden" name="telcontrab" value="нет">
</td>
</tr>
<tr>
<td valign="top" class="header" colspan=2>
ОСНОВНАЯ ИНФОРМАЦИЯ:
</td>
</tr>
<tr>
<td align=right>Дата рождения:</td>
<td>
год:<select name="brnyear">
<option>1950</option>
<option>1951</option>
<option>1952</option>
<option>1953</option>
<option>1954</option>
<option>1955</option>
<option>1956</option>
<option>1957</option>
<option>1958</option>
<option>1959</option>
<option>1960</option>
<option>1961</option>
<option>1962</option>
<option>1963</option>
<option>1964</option>
<option>1965</option>
<option>1966</option>
<option>1967</option>
<option>1968</option>
<option>1969</option>
<option selected>1970</option>
<option>1971</option>
<option>1972</option>
<option>1973</option>
<option>1974</option>
<option>1975</option>
<option>1976</option>
<option>1977</option>
<option>1978</option>
<option>1979</option>
<option>1980</option>
<option>1981</option>
<option>1982</option>
<option>1983</option>
<option>1984</option>
<option>1985</option>
<option>1986</option>
<option>1987</option>
<option>1988</option>
<option>1989</option>
<option>1990</option>
</select>
месяц:<select name="brnmnth">
<option selected>01</option>
<option>02</option>
<option>03</option>
<option>04</option>
<option>05</option>
<option>06</option>
<option>07</option>
<option>08</option>
<option>09</option>
<option>10</option>
<option>11</option>
<option>12</option>
</select>
день:<select name="brnday">
<option selected>01</option>
<option>02</option>
<option>03</option>
<option>04</option>
<option>05</option>
<option>06</option>
<option>07</option>
<option>08</option>
<option>09</option>
<option>10</option>
<option>11</option>
<option>12</option>
<option>13</option>
<option>14</option>
<option>15</option>
<option>16</option>
<option>17</option>
<option>18</option>
<option>19</option>
<option>20</option>
<option>21</option>
<option>22</option>
<option>23</option>
<option>24</option>
<option>25</option>
<option>26</option>
<option>27</option>
<option>28</option>
<option>29</option>
<option>30</option>
<option>31</option>
</select>
<input type="hidden" name="child" value="нет">
<input type="hidden" name="drivecat" value="нет">
<input type="hidden" name="drivelong" value="нет">
</td>
</tr>
<tr> 
<td align=right>Базовое образование: </td>
<td> 
<select name="obraz">
<option>нет</option>
<option selected>среднее</option>
<option>среднее специальное</option>
<option>неоконченное высшее</option>
<option>высшее</option>
</select>
<input type="hidden" name="child" value="нет">
<input type="hidden" name="obrazform" value="нет"> 
<input type="hidden" name="vuzkvalific" value="нет">
<input type="hidden" name="vuzdop" value="нет">
<input type="hidden" name="vuzdopgod" value="0">
<input type="hidden" name="vuzdoplong" value="нет"> 
<input type="hidden" name="programs" value="нет">
<input type="hidden" name="forlang" value="нет">
<input type="hidden" name="pogelan" value="нет">
<input type="hidden" name="programs" value="нет">
<input type="hidden" name="workoplold" value="нет">
<tr> 
<td align=right>Требуемая зарплата:</td>
<td>
<input type="text" name="workoplnew" value="до 200 грн" size="30" maxlength="30"> 
<input type="hidden" name="workbegin" value="нет">
<input type="hidden" name="workend" value="нет">
<input type="hidden" name="comandirovki" value="нет">
<input type="hidden" name="comanprocent" value="нет">
<input type="hidden" name="worksfera" value="нет">
<input type="hidden" name="workdolgnold" value="нет">
<input type="hidden" name="workdolgnlong" value="нет">
<input type="hidden" name="dolgobazan" value="нет">
<input type="hidden" name="adrsoiscat" value="нет">
<input type="hidden" name="dolgobazan" value="нет">
<input type="hidden" name="dolgobazan" value="нет">
<input type="hidden" name="dolgobazan" value="нет">
<input type="hidden" name="dolgobazan" value="нет">
<input type="hidden" name="dolgobazan" value="нет">
<input type="hidden" name="adrsoiscatprop" value="нет">
</td>
</tr>
<tr>
<td align=right valign=top>Дополнительная
информация:</td>
<td><textarea name="dopoln" cols="70" rows="15"></textarea>
</td>
</tr>
<tr>
<td valign="top" class="header" colspan=2>
ТЕСТ:
</td>
</tr>
<tr> 
<tr>
<td valign="top" colspan=2>
Оцените по 10 - бальной системе значение  для Вас данных факторов ( 1 - максимальное, 10 - минимальное значение, <font size=2 color="red">(значения не должны повторяться)</font>:</b>
</td>
</tr>
<tr> 
<td colspan="2"> 
<table border="0" align=center cellspacing="2" cellpadding="2" class='regular'>
<tr> 
<td>1.Карьера- </td>
<td>
<select name="test101">
<option selected>1</option>
<option>2</option>
<option>3</option>
<option>4</option>
<option>5</option>
<option>6</option>
<option>7</option>
<option>8</option>
<option>9</option>
<option>10</option>
</select>
<input type="hidden" name="test102" value="0">
<input type="hidden" name="test103" value="0">
</td>
<td>2.Деньги , льготы- </td>
<td>
<select name="test104">
<option>1</option>
<option>2</option>
<option>3</option>
<option selected>4</option>
<option>5</option>
<option>6</option>
<option>7</option>
<option>8</option>
<option>9</option>
<option>10</option>
</select>
</td>
<td>3.Приобретение опыта- </td>
<td>
<select name="test105">
<option>1</option>
<option>2</option>
<option>3</option>
<option>4</option>
<option selected>5</option>
<option>6</option>
<option>7</option>
<option>8</option>
<option>9</option>
<option>10</option>
</select>
</td>
</tr>
<tr> 
<td>4.Дружелюбный коллектив- </td>
<td>
<select name="test106">
<option>1</option>
<option>2</option>
<option>3</option>
<option>4</option>
<option>5</option>
<option selected>6</option>
<option>7</option>
<option>8</option>
<option>9</option>
<option>10</option>
</select>
</td>
<td>5.Стабильность- </td>
<td colspan=3>
<select name="test107">
<option>1</option>
<option>2</option>
<option>3</option>
<option>4</option>
<option>5</option>
<option> 6</option>
<option selected>7</option>
<option>8</option>
<option>9</option>
<option>10</option>
</select>
<input type="hidden" name="test108" value="0">
<input type="hidden" name="test109" value="0">
<input type="hidden" name="test110" value="0">
<input type="hidden" name="test201" value="0">
<input type="hidden" name="test202" value="0">
<input type="hidden" name="test203" value="0">
<input type="hidden" name="test204" value="0">
<input type="hidden" name="test205" value="0">
<input type="hidden" name="test206" value="0">
<input type="hidden" name="test207" value="0">
<input type="hidden" name="test208" value="0">
<input type="hidden" name="test209" value="0">
<input type="hidden" name="test210" value="0">
<input type="hidden" name="test211" value="0">
<input type="hidden" name="test212" value="0">
<input type="hidden" name="test213" value="0">
<input type="hidden" name="test214" value="0">
<input type="hidden" name="test215" value="0">
<input type="hidden" name="test216" value="0">
<input type="hidden" name="test217" value="0">
<input type="hidden" name="test218" value="0">
<input type="hidden" name="fionextrecom" value="0">
<input type="hidden" name="dolgnextrecom" value="0">
<input type="hidden" name="contnextrecom" value="0">
<input type="hidden" name="officeoldadr" value="0">
<input type="hidden" name="officeoldin" value="0">
<input type="hidden" name="officeoldout" value="0">
<input type="hidden" name="officeoldshtat" value="0">
<input type="hidden" name="officeoldshtatmain" value="0">
<input type="hidden" name="officeolddost" value="0">
<input type="hidden" name="officeolduvoln" value="0">
<input type="hidden" name="officeoldin" value="0">
<input type="hidden" name="officelastadr" value="0">
<input type="hidden" name="officelastin" value="0">
<input type="hidden" name="officelastout" value="0">
<input type="hidden" name="officelastshtat" value="0">
<input type="hidden" name="officelastshtatmain" value="0">
<input type="hidden" name="officelastdost" value="0">
<input type="hidden" name="officelastuvoln" value="0">
<input type="hidden" name="infosource" value="0">
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td align=center colspan=2>
<INPUT onclick=check_anketa(this.form) type=button value=Отослать name=button>
<input type="reset" value="Очистить">
</td>
</tr>
</table>
</form>