<form  method="post" target="_blank" action='http://<?=$host?>/recruiting/addvac.php'>
<table cellpadding="3" cellspacing="0" border="0" bgcolor='#E5E5E5' width=100% align=center>
<td colspan="2"><marquee><font color="red"><b>УБЕДИТЕЛЬНО ПРОСИМ ВАС ВНИМАТЕЛЬНО ЗАПОЛНЯТЬ ДАННЫЕ!</b></font></marquee><br></td>
</tr>
<tr>
<td valign="top" class="header" colspan=2>
СФЕРЫ ДЕЯТЕЛЬНОСТИ (можно указать от 1 до 3):
</td>
</tr>
<tr>
<td colspan="2">
<select name="sfera1">
<option selected>торговля продукты питания</option>
<option>торговля тнп</option>
<option>торговля техника</option>
<option>торговля телекоммуникации и связь</option>
<option>торговля розничная</option>
<option>кадровые службы, рекруитмент</option>
<option>секреториат, ахо</option>
<option>информационно - технические службы</option>
<option>импорт, экспорт</option>
<option>логистика, таможня, склад</option>
<option>перевозки, автобизнес</option>
<option>производство продуктов питания</option>
<option>производство швейное</option>
<option>производство мебельное</option>
<option>производство разное</option>
<option>информационные технологии</option>
<option>медицина, косметология, фармация</option>
<option>бухгалтерия и аудит</option>
<option>финансы и ценные бумаги</option>
<option>банковская  сфера</option>
<option>юриспруденция и нотариат</option>
<option>страхование</option>
<option>строительство,  ремонт, архитектура</option>
<option>недвижимость</option>
<option>сми: телевидение, радиовещание, пресса</option>
<option>реклама, дизайн, общественные связи</option>
<option>издательское дело и полиграфия</option>
<option>маркетинг</option>
<option>охрана и безопасность</option>
<option>туристический бизнес</option>
<option>игорный и шоу бизнес, досуг, мода, спорт</option>
<option>охрана и безопасность</option>
<option>гостиничный бизнес</option>
<option>общественное питание и ресторанный бизнес</option>
<option>бытовое и жилищно - комунальное обслуживание</option>
<option>воспитание, образование</option>
<option>научно - исследовательская и проектно - конструкторская деятельность</option>
<option>аварийно - спасательные и пожарные службы</option>
<option>культура и искусство</option>
<option>геология, геодезия, картография</option>
<option>благотворительная, социальная, религиозная и культурная деятельность</option>
<option>санитария, эпидемиология, мониторинг окружающей среды</option>
<option>работа за рубежом</option>
<option>работа, не требующая специальной подготовки, и - у  частных лиц</option>
<option>разное</option>
</select>
<br>
<br>
<select name="sfera2">
<option selected>данных нет</option>
<option>торговля продукты питания</option>
<option>торговля тнп</option>
<option>торговля техника</option>
<option>торговля телекоммуникации и связь</option>
<option>торговля розничная</option>
<option>кадровые службы, рекруитмент</option>
<option>секреториат, ахо</option>
<option>информационно - технические службы</option>
<option>импорт, экспорт</option>
<option>информационные технологии</option>
<option>логистика, таможня, склад</option>
<option>перевозки, автобизнес</option>
<option>производство продуктов питания</option>
<option>производство швейное</option>
<option>производство мебельное</option>
<option>производство разное</option>
<option>медицина, косметология, фармация</option>
<option>бухгалтерия и аудит</option>
<option>финансы и ценные бумаги</option>
<option>банковская  сфера</option>
<option>юриспруденция и нотариат</option>
<option>страхование</option>
<option>строительство,  ремонт, архитектура</option>
<option>недвижимость</option>
<option>сми: телевидение, радиовещание, пресса</option>
<option>реклама, дизайн, общественные связи</option>
<option>издательское дело и полиграфия</option>
<option>маркетинг</option>
<option>охрана и безопасность</option>
<option>туристический бизнес</option>
<option>игорный и шоу бизнес, досуг, мода, спорт</option>
<option>охрана и безопасность</option>
<option>гостиничный бизнес</option>
<option>общественное питание и ресторанный бизнес</option>
<option>бытовое и жилищно - комунальное обслуживание</option>
<option>воспитание, образование</option>
<option>научно - исследовательская и проектно - конструкторская деятельность</option>
<option>аварийно - спасательные и пожарные службы</option>
<option>культура и искусство</option>
<option>геология, геодезия, картография</option>
<option>благотворительная, социальная, религиозная и культурная деятельность</option>
<option>санитария, эпидемиология, мониторинг окружающей среды</option>
<option>работа за рубежом</option>
<option>работа, не требующая специальной подготовки, и - у  частных лиц</option>
<option>разное</option>
</select>
<br>
<br>
<select name="sfera3">
<option selected>данных нет</option>
<option>торговля продукты питания</option>
<option>торговля тнп</option>
<option>торговля техника</option>
<option>торговля телекоммуникации и связь</option>
<option>торговля розничная</option>
<option>кадровые службы, рекруитмент</option>
<option>секреториат, ахо</option>
<option>информационно - технические службы</option>
<option>импорт, экспорт</option>
<option>логистика, таможня, склад</option>
<option>перевозки, автобизнес</option>
<option>производство продуктов питания</option>
<option>производство швейное</option>
<option>производство мебельное</option>
<option>производство разное</option>
<option>медицина, косметология, фармация</option>
<option>бухгалтерия и аудит</option>
<option>финансы и ценные бумаги</option>
<option>банковская  сфера</option>
<option>юриспруденция и нотариат</option>
<option>страхование</option>
<option>строительство,  ремонт, архитектура</option>
<option>недвижимость</option>
<option>сми: телевидение, радиовещание, пресса</option>
<option>реклама, дизайн, общественные связи</option>
<option>издательское дело и полиграфия</option>
<option>маркетинг</option>
<option>охрана и безопасность</option>
<option>туристический бизнес</option>
<option>игорный и шоу бизнес, досуг, мода, спорт</option>
<option>охрана и безопасность</option>
<option>гостиничный бизнес</option>
<option>общественное питание и ресторанный бизнес</option>
<option>бытовое и жилищно - комунальное обслуживание</option>
<option>воспитание, образование</option>
<option>научно - исследовательская и проектно - конструкторская деятельность</option>
<option>аварийно - спасательные и пожарные службы</option>
<option>культура и искусство</option>
<option>геология, геодезия, картография</option>
<option>благотворительная, социальная, религиозная и культурная деятельность</option>
<option>санитария, эпидемиология, мониторинг окружающей среды</option>
<option>работа за рубежом</option>
<option>работа, не требующая специальной подготовки, и - у  частных лиц</option>
<option>разное</option>
</select>
<input type="hidden" name="sfera4" value="данных нет">
<input type="hidden" name="sfera5" value="данных нет">
</td>
</tr>
<tr>
<td valign="top" class="header" colspan=2>
КОНТАКТНАЯ ИНФОРМАЦИЯ:
</td>
</tr>
<tr>
<td align=right>Лицо, делающее заказ:</td>
<td><input type="text" name="fioquery" value="" size="70" maxlength="40">
<input type="hidden" name="fiocontact" value="нет">
<input type="hidden" name="fionaim" value="данных нет">
<input type="hidden" name="officename" value="данных нет">
<input type="hidden" name="obrazdate" value="данных нет">
</td>
</tr>
<tr>
<td align=right>Регион:</td>
<td>
<SELECT size=1 name=strana> 
<OPTION value='Винница'>Винница</OPTION> 
<OPTION value='Днепропетровск' selected>Днепропетровск</OPTION> 
<OPTION value='Донецк'>Донецк</OPTION>
<OPTION value='Житомир'>Житомир</OPTION> 
<OPTION value='Закарпатье'>Закарпатье</OPTION> 
<OPTION value='Запорожье'>Запорожье</OPTION> 
<OPTION value='Ивано-Франковск'>Ивано-Франковск</OPTION> 
<OPTION value='Киев'>Киев</OPTION> 
<OPTION value='Кировоград'>Кировоград</OPTION> 
<OPTION value='Крым'>Крым</OPTION> 
<OPTION value='Луганск'>Луганск</OPTION> 
<OPTION value='Луцк'>Луцк</OPTION> 
<OPTION value='Львов'>Львов</OPTION> 
<OPTION value='Николаев'>Николаев</OPTION> 
<OPTION value='Одесса'>Одесса</OPTION>
<OPTION value='Полтава'>Полтава</OPTION> 
<OPTION value='Ровно'>Ровно</OPTION>
<OPTION value='Сумы'>Сумы</OPTION> 
<OPTION value='Тернополь'>Тернополь</OPTION>
<OPTION value='Харьков'>Харьков</OPTION>
<OPTION value='Херсон'>Херсон</OPTION> 
<OPTION value='Хмельницкий'>Хмельницкий</OPTION> 
<OPTION value='Черкассы'>Черкассы</OPTION> 
<OPTION value='Чернигов'>Чернигов</OPTION>
<OPTION value='Черновцы'>Черновцы</OPTION> 
<OPTION value='Россия'>Россия</OPTION> 
<OPTION value='Остальные страны'>Остальные страны</OPTION>
</SELECT>
<input type="hidden" name="officeadr" value="данных нет">
</td>
</tr>
<tr>
<td align=right>
связь:
</td>
<td colspan=2>Телефон:
<input type="text" name="officephone" value="" size="15" maxlength="15">
Факс:
<input type="text" name="officefax" value="" size="15" maxlength="15">
e-mail:
<input type="text" name="officeemail" value="" size="15" maxlength="15">
<input type="hidden" name="jurstat" value="нет">
<input type="hidden" name="tipbiz" value="нет">
<input type="hidden" name="vidpro" value="нет">
</td>
</tr>
<tr>
<td valign="top" class="header" colspan=2>
ОСНОВНАЯ ИНФОРМАЦИЯ:
</td>
</tr>
<tr>
<td align=right>Требуемый специалист:</td>
<td><input type="text" name="specialist" value="" size="40" maxlength="40">
<input type="hidden" name="pvacan" value="нет">
<input type="hidden" name="podchi" value="нет">
<input type="hidden" name="objazan" value="нет">
</td>
</tr>
<tr>
<td align=right>Возраст (от и до):</td>
<td>от <input type="text" name="minvoz"  size="5" maxlength="5">
до<input type="text" name="maxvoz"  size="5" maxlength="5">
</td>
</tr>
<tr>
<td align=right>Пол:</td>
<td>		
<input type="radio" name="pol" value="жен">жен
<input type="radio" name="pol" value="муж">муж
<input type="radio" name="pol" value="любой" checked>любой       
</td>
</tr>
<tr>
<td align=right>Образование:</td>
<td>
<SELECT size=1 name=obrazow>
<OPTION value='не имеет значения' selected>не имеет значения</OPTION>
<OPTION value='высшее'>высшее</OPTION>
<OPTION value='средне-специальное'>средне-специальное</OPTION>
<OPTION value='среднее'>среднее</OPTION>
</SELECT>
<input type="hidden" name="opytrab" value="нет">
<input type="hidden" name="drivecat" value="нет">
<input type="hidden" name="persauto" value="нет">
<input type="hidden" name="comanprocent" value="нет">
<input type="hidden" name="forlang" value="нет">
<input type="hidden" name="programs" value="нет">
<input type="hidden" name="persauto" value="нет">
</td>
</tr>
<tr>
<td align=right>График работы:</td>
<td>
<table border="0" summary="" class='regular'>
<tr>
<td align=right>Самое раннее с </td>
<td colspan="2">
<select name="workbegin">
<option>не имеет значения</option>
<option>5</option>
<option>6</option>
<option>7</option>
<option selected>8</option>
<option>9</option>
<option>10</option>
<option>11</option>
<option>12</option>
</select>
часов
</td>
</tr>
<tr>
<td>Самое позднее до </td>
<td colspan="2">
<select name="workend">
<option>не имеет значения</option>
<option>14</option>
<option>15</option>
<option>16</option>
<option  selected>17</option>
<option>18</option>
<option>19</option>
<option>20</option>
<option>21</option>
<option>22</option>
<option>23</option>
<option>24</option>
</select>
часов
<input type="hidden" name="obedstart" value="нет">
<input type="hidden" name="obedstop" value="нет">
<input type="hidden" name="ispsroc" value="нет">
<input type="hidden" name="otpusk" value="нет">
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td align=right>Заработная плата:</td>
<td>
<table border="0" summary="" class='regular'>
<tr>
<td align=right>На испытательный срок:</td>
<td><input type="text" name="payispsroc" size="30" maxlength="30"></td>
</tr>
<tr>
<td align=right>В штате:</td>
<td><input type="text" name="payshtat" size="30" maxlength="30"></td>
</tr>
</table>
<input type="hidden" name="bonus" value="нет">
<input type="hidden" name="kompens" value="нет">
<input type="hidden" name="doplgot" value="нет">
</td>
</tr>
<tr>
<td align=right valign=top>Дополнительная
информация:</td>
<td><textarea name="other" cols="70" rows="15"></textarea>
</td>
</tr>
<tr>
<td colspan=2 align=center>
<INPUT onclick=check_sworker(this.form) type=button value=Отослать name=button>
<input type="reset" value="Очистить">
</td>
</tr>
</table>
</form>