<table cellpadding="2" cellspacing="0" border="1" width=100%>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=adanketa">ввод резюме</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=adsworker">ввод вакансии</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=adcform">ввод информации о фирме</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=adnews">добавить новость на сайт</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=adkurst">добавить курсиста</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=vacances">просмотр вакансий</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=resumes">просмотр резюме</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=firms">просмотр фирм</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=news">просмотр новостей сайта</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=kursist">просмотр курсистов</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=subm">рассылка</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=partners">партнеры</a></td>
</tr>
<tr> 
<td valign="top" class="grey"><a href="index.php?id=edit">редактирование тренингов</a></td>
</tr>
</table>