<hr color=navy>
<div align="center">
<font class='small'  color="white" size="1"> &copy; 2003 ASTRAGAL Все права защищены.<br>
Использование материалов с данного сайта возможно только <br>
с письменного разрешения компании <a href="http://<?=$website1?>" target="new">ASTRAGAL</a>.
<br><br>
Дизайн и программирование: by <a href="mailto:damien@ua.fm">damien</a> (<a href="http://www.webclick.dp.ua" target=blank>webclick group</a>)</font></center>
</div>