<tr>
<td valign="top" class="header">"горячие"
</td>
</tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/recruiting?id=resumhot'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Резюме
</td>
</tr>
<tr>
<TD onmouseover="this.style.backgroundColor='#CCFFFF';this.style.cursor='hand';"         onclick="parent.location='/recruiting?id=vacanhot'" onmouseout="this.style.backgroundColor='#E5E5E5'" valign=top bgColor=#e5e5e5> 
Вакансии
</td>
</tr>
