<center>
<!-- bigmir)net TOP 100 GIF 1x1 -->
<span id='obHP'></span>
<script language="javascript"><!--
bmQ='<img src=http://c.bigmir.net/?s48184&t6'
bmD=document
bmD.cookie="b=b"
if(bmD.cookie)bmQ+='&c1'
//--></script>
<script language='jscript'><!--
obHP.style.behavior="url('#default#homePage')";
obHP.addBehavior('#default#homePage');
if(obHP.isHomePage(window.location.href))bmQ+='&h1';
//-->
</script>
<script language="javascript1.2"><!-- 
bmS=screen;bmQ+='&d'+(bmS.colorDepth?bmS.colorDepth:bmS.pixelDepth)+"&r"+bmS.width;
//--></script><script language="javascript"><!--
bmF = bmD.referrer.slice(7);
((bmI=bmF.indexOf('/'))!=-1)?(bmF=bmF.substring(0,bmI)):(bmI=bmF.length);
if(bmF!=window.location.href.substring(7,7+bmI))bmQ+='&f'+escape(bmD.referrer);
bmD.write(bmQ+" border=0 width=1 height=1>");
//--></script>
<!-- bigmir)net TOP 100 -->
<a href=http://www.bigmir.net/?cl=48184>
<img src=http://c.bigmir.net/?s48184&t18&l1 width=88 height=63 border=0 alt="bigmir)net TOP 100"></a>
<!-- bigmir)net TOP 100 -->

<!--begin of Rambler's Top100 code -->
<a href="http://top100.rambler.ru/top100/">
<img src="http://counter.rambler.ru/top100.cnt?460447" alt="" width=1 height=1 border=0></a>
<!--end of Top100 code-->
<!--begin of Top100 logo -->
<a href="http://top100.rambler.ru/top100/">
<img src="http://top100-images.rambler.ru/top100/w3.gif" alt="Rambler's Top100" width=88 height=31 border=0></a>
<!--end of Top100 logo -->

<a href="http://list.mail.ru"><img
src="http://list.mail.ru/img/listru-a21.gif"
width="88" height="31" border="0"
alt="Каталог@MAIL.RU - каталог ресурсов интернет"></a>

<!-- begin of Pautina.net code -->
<a href="http://www.pautina.net/" target=_blank>
<img src="http://www.pautina.net/images/pautina88.gif" alt="каталог @PAUTINA.NET" width=88 height=31 border=0></a>
<!-- end of Pautina.net code -->

<!-- begin of ulitka code --><a href="http://www.ulitka.ru"><img src="http://www.ulitka.ru/img/ulitka.gif"width="88" height="31" alt="Каталог Ресурсов Интернет" border="0"></a><!-- end of ulitka code -->

<a href="http://www.uaportal.com"><img src="http://www.uaportal.com/banners/8831_1.gif" width=88 height=31 alt="Украинский портАл" border=0></a> 

<a href="http://www.nashe.ua"><img src="http://www.nashe.ua/includes/services/catalog/buttons/88.gif" width="88" height="31" border="0" alt="Nashe.ua - здесь есть все!"></a>

<a href="http://zona.dp.ua/dir/in.php?id=12443" target=_top>
<img src="http://zona.dp.ua/Images/zona.gif" width=88 height=31 border=0 alt="Днепропетровский каталог веб ресурсов"></a>

<a target="_top" href="http://www.lookup.ru">
<img src="http://www.lookup.ru/click.gif" border=0 width=88 heigh=31 alt='"LookUp". Ресурсы сети Интернет'></a>

<a href="http://www.silver.kiev.ua" target="_blank"><img src="http://www.silver.kiev.ua/img/silver-knopka.gif" width="88" height="31" border="0" alt="silver.kiev.ua"></a>

<a href="http://www.linkfinest.ru/ref.php?id=16908">
<img src="http://www.linkfinest.ru/banner/catalog_russia.gif" border="0" 
alt="www.LinkFinest.ru - Аннотированный каталог ресурсов интернет. Система поиска по каталогу." 
width="88" height="31"></a>

<a href="http://www.ualist.com" target="_blank"><img src="http://www.ualist.com/buttons/blue.gif" width="88" height="31" border="0" alt="Каталог UaList.com"></a>

<A HREF="http://www.zabor.com/" target=_top><IMG SRC="http://www.zabor.com/search/search.gif" BORDER=0 ALT="Поиск в каталоге ZABOR.COM" width=88 height=31></A>

<a href="http://www.ibn.ru/cgi-bin/asp.pl?_50128">
<img src="http://www.ibn.ru/asp/pic/ibn8831.gif" 
width=88 height=31 border=0 alt="IBN.RU - Информационная Деловая Сеть"></a>

<A HREF="http://www.joblist.ru/analit_sois.shtml" TARGET="_blank" ><IMG SRC="http://www.joblist.ru/b/JobListBut002.gif" WIDTH="88" HEIGHT ="31" ALT="JobList.Ru" BORDER=0></A>
</center>