<!-- Ukrainian Banner Network 100x100 START -->
<script>
//<!--
user = "17995";
page = "1";
pid = Math.round((Math.random() * (10000000 - 1)));
document.write("<iframe src='http://banner.kiev.ua/cgi-bin/bi.cgi?h" +
user + "&"+ pid + "&" + page + "&2' frameborder=0 vspace=0 hspace=0 " +
" width=100 height=100 marginwidth=0 marginheight=0 scrolling=no>");
document.write("<a href='http://banner.kiev.ua/cgi-bin/bg.cgi?" +
user + "&"+ pid + "&" + page + "&2' target=_top>");
document.write("<img border=0 src='http://banner.kiev.ua/" +
"cgi-bin/bi.cgi?i" + user + "&" + pid + "&" + page +
"&2' width=100 height=100 alt='Украинская баннерная сеть'></a>");
document.write("</iframe>");
//-->
</script><br><br>
<a href="http://banner.kiev.ua" 
target=_top><img src="http://banner.kiev.ua/dividers/d100-1.gif" 
width="100" height="15" border="0" alt="Украинские 100x100"></a><br><br>
<script>
//<!--
user = "17995";
page = "1";
pid = Math.round((Math.random() * (10000000 - 1)));
document.write("<iframe src='http://banner.kiev.ua/cgi-bin/bi.cgi?h" +
user + "&"+ pid + "&" + page + "&2' frameborder=0 vspace=0 hspace=0 " +
" width=100 height=100 marginwidth=0 marginheight=0 scrolling=no>");
document.write("<a href='http://banner.kiev.ua/cgi-bin/bg.cgi?" +
user + "&"+ pid + "&" + page + "&2' target=_top>");
document.write("<img border=0 src='http://banner.kiev.ua/" +
"cgi-bin/bi.cgi?i" + user + "&" + pid + "&" + page +
"&2' width=100 height=100 alt='Украинская баннерная сеть'></a>");
document.write("</iframe>");
//-->
</script>
<!-- Ukrainian Banner Network 100x100 END -->
